[package]
name = "bustin_solutions"
version = "0.1.0"
authors = ["Jon Daniel <me@jondaniel.email>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
chrono = "0.4"
chrono-tz = "0.5"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
